# GestureBind Default Configuration

app:
  version: "1.0.0"
  save_user_data_path: "./data"
  log_level: "info"
  trained_gestures_path: "./data/gestures"  # Path relative to workspace

camera:
  device_id: 0
  width: 640
  height: 480
  fps: 30
  flip_horizontal: true  # Mirror camera feed for more intuitive gestures

detection:
  engine: "mediapipe"  # Options: mediapipe, yolov8, mock
  confidence_threshold: 0.7
  cooldown_ms: 500  # Cooldown between gesture detections to prevent rapid triggering
  min_detection_duration_ms: 200  # Minimum duration a gesture must be held to trigger

# Preprocessing options for optimizing detection
preprocessing:
  use_grayscale: false  # Convert to grayscale for faster processing
  resize_frame: false   # Resize input frame for processing
  resize_width: 320     # Width to resize to if resize_frame is true
  resize_height: 240    # Height to resize to if resize_frame is true
  use_roi: false        # Use region of interest to focus detection
  roi_x: 100            # ROI starting X coordinate
  roi_y: 100            # ROI starting Y coordinate
  roi_width: 440        # ROI width
  roi_height: 280       # ROI height

ui:
  theme: "system"  # Options: system, light, dark
  minimize_to_tray: true
  start_minimized: false
  overlay_feedback: true
  overlay_timeout_ms: 1500
  show_preview: true
  show_fps: true
  camera_preview_fps: 15  # UI update rate for camera preview (to reduce CPU usage)

actions:
  default_profile: "default"
  enable_shortcuts: true
  gesture_trigger_mode: "single"  # Options: single, continuous, toggle

profiles:
  default:
    gesture_mappings: {}  # Empty default profile - use trained gestures instead of predefined ones
  
  media:
    gesture_mappings: {}  # Empty media profile
  
  presentation:
    gesture_mappings: {}  # Empty presentation profile

# Advanced settings (for developers and power users)
advanced:
  debug_mode: false
  gesture_data_folder: "./data/gestures"
  model_folder: "./data/models"
  max_log_files: 10
  max_log_size_mb: 5
  landmark_smoothing: true    # Apply smoothing to landmarks for more stable detection
  smoothing_factor: 0.5       # Smoothing factor (0-1, lower = more smoothing)
  smoothing_window: 3         # Window size for historical smoothing

# Paths for models and data
paths:
  model_folder: "./data/models"
  gesture_data_folder: "./data/gestures"